export const API = 'http://127.0.0.1:8000'


//NOTICE
export const SHOW_NOTICE = 'SHOW_NOTICE'
export const HIDE_NOTICE = 'HIDE_NOTICE'

//LOADING
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

//REVENUE
export const GET_LIST_REVENUE = 'GET_LIST_REVENUE'
export const GET_LIST_REVENUE_SUCCESS = 'GET_LIST_REVENUE_SUCCESS'
export const GET_LIST_REVENUE_ERROR = 'GET_LIST_REVENUE_ERROR'

export const DELETE_REVENUE = 'DELETE_REVENUE'
export const DELETE_REVENUE_SUCCESS = 'DELETE_REVENUE_SUCCESS'
export const DELETE_REVENUE_ERROR = 'DELETE_REVENUE_ERROR'